# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        master.storage.sftp:
            adapter: 'sftp'
            options:
                host: u259566.your-storagebox.de
                port: 22
                username: u259566-sub1
                password: null
                privateKey: ../filesystem_master_private_key
                root: master
                timeout: 10
                directoryPerm: 0744
                permPublic: 0700
                permPrivate: 0744
        master.storage:
            adapter: 'lazy'
            options:
                source: '%env(MASTER_STORAGE)%'
