# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/blob/release/3.x/Resources/doc/index.md
oneup_flysystem:
    adapters:
        master_local_adapter:
            local:
                directory: '%env(UPLOAD_DIR)%'
        master_sftp_adapter:
            sftp:
                host: u259566.your-storagebox.de
                port: ~
                username: u259566-sub1
                password: null
                root: master
                timeout: ~
                privateKey: ../filesystem_master_private_key
                permPrivate: ~
                permPublic: ~
                directoryPerm: ~
    filesystems:
        master_filesystem:
            adapter: 'master_sftp_adapter'
            alias: master_filesystem

