security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # in_memory: { memory: ~ }
        default_provider:
            entity: { class: App\Entity\ManiaplanetUser }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            logout:
                path:   /logout
                target: /
            guard:
                authenticators:
                    - App\Security\OAuth2\ManiaplanetAuthenticator
            # this should avoid problems of session timeout during upload
#            remember_me:
#                secret:   '%kernel.secret%' # used to encrypt the cookie
#                lifetime: 86400 # 1 day in seconds
#                path:     / # remember me applies everywhere
#                always_remember_me: true # don't ask the user if he wants to be remembered

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER # ROLE_ADMIN inherits ROLE_USER
        ROLE_BANNED: ROLE_USER
    
    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/browse, roles: ROLE_USER }
