homepage:
    path: /
    controller: App\Controller\HomeController::show
    
admin_review:
    path: /admin/review
    controller: App\Controller\Admin\ReviewController::show
    
admin_review_download:
    path: /admin/review/download
    controller: App\Controller\Admin\ReviewController::download

admin_users:
    path: /admin/users
    controller: App\Controller\Admin\UsersController::show

privacy:
    path: /privacy
    controller: App\Controller\PrivacyController::show

browse:
    path: /browse
    controller: App\Controller\BrowseController::show

login:
    path: /login
    controller: App\Security\OAuth2\ManiaplanetAuthenticator::start

logout:
    path: /logout
    # no controller needed

# login route should redirect the user here
connect_maniaplanet:
    path: /connect/maniaplanet
    controller: App\Controller\ManiaplanetController::connectAction

# shown after the login process finished
connect_maniaplanet_finish:
    path: /connect/maniaplanet/finish
    controller: App\Controller\ManiaplanetController::finish

# dynamic route for the uploader
oneup_uploader:
    resource: .
    type: uploader
