homepage:
    path: /
    controller: App\Controller\HomeController::show
    
admin_review:
    path: /admin/review
    controller: App\Controller\Admin\ReviewController::show
    
admin_review_download:
    path: /admin/review/download
    controller: App\Controller\Admin\ReviewController::download

admin_users:
    path: /admin/users
    controller: App\Controller\Admin\UsersController::show

admin_settings:
    path: /admin/settings
    controller: App\Controller\Admin\SettingsController::show

privacy:
    path: /privacy
    controller: App\Controller\PrivacyController::show

browse:
    path: /browse
    controller: App\Controller\BrowseController::show

browser_locs_download:
    path: /locs_download
    controller: App\Controller\DownloadLogsController::download

user:
    path: /user
    controller: App\Controller\UserController::show

user_set_notification_settings:
    path: /user/set_notification_settings
    controller: App\Controller\UserController::setNotificationSettings

# login route should redirect the user here
connect_maniaplanet:
    path: /connect/maniaplanet
    controller: App\Controller\ManiaplanetController::connectAction

logout:
    path: /logout
    # no controller needed

# shown after the login process finished
connect_maniaplanet_finish:
    path: /connect/maniaplanet/finish
    controller: App\Controller\ManiaplanetController::finish

process_upload:
    path: /upload/process
    controller: App\Controller\UploadController::upload
